import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { css, cx } from "../../styled-system/css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// 모든 page의 공통 레이아웃

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={cx(css({ bg: "white" }), inter.className)}>
				LOOT LAYOUT
				{children}
			</body>
		</html>
	);
}

// 주소가 localhost:3001일 때는 children->page.tsx, modal->@modal/default.tsx
// 주소가 localhost:3001/i/flow/login 때는 chldren->i/flow/login/page.tsx, modal->@modal/i/flow/login/page.tsx
